const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const phase3Dir = path.join(root, "src", "phase3");
const outFile = path.join(root, "src", "phase3_full_collect.js");

const modules = [
    "config.js",
    "text_utils.js",
    "screen.js",
    "time.js",
    "account_parser.js",
    "series_parser.js",
    "ocr.js",
    "csv_store.js",
    "actions.js",
    "reporter.js",
    "main.js"
];

function normalizeSlashes(s) {
    return s.replace(/\\/g, "/");
}

function moduleBody(name) {
    const fullPath = path.join(phase3Dir, name);
    return fs.readFileSync(fullPath, "utf8");
}

const lines = [];
lines.push('"auto";');
lines.push("");
lines.push("// Generated by tools/build_phase3_full_collect.js.");
lines.push("// Edit files under src/phase3/, then rebuild this single-file entry for VSCode Auto.js remote runs.");
lines.push("(function () {");
lines.push("    var __phase3Factories = {};");
lines.push("    var __phase3Cache = {};");
lines.push("");
lines.push("    function __phase3Normalize(id) {");
lines.push("        id = String(id || '').replace(/\\\\/g, '/');");
lines.push("        if (id.indexOf('./') === 0) id = id.substring(2);");
lines.push("        return id;");
lines.push("    }");
lines.push("");
lines.push("    function __phase3Require(id) {");
lines.push("        id = __phase3Normalize(id);");
lines.push("        if (__phase3Cache[id]) return __phase3Cache[id].exports;");
lines.push("        var factory = __phase3Factories[id];");
lines.push("        if (!factory) throw new Error('Phase3 bundled module not found: ' + id);");
lines.push("        var module = { exports: {} };");
lines.push("        __phase3Cache[id] = module;");
lines.push("        factory(__phase3Require, module, module.exports);");
lines.push("        return module.exports;");
lines.push("    }");
lines.push("");

modules.forEach((name) => {
    lines.push("    __phase3Factories[" + JSON.stringify(normalizeSlashes(name)) + "] = function (require, module, exports) {");
    const body = moduleBody(name).replace(/\r\n/g, "\n").replace(/\r/g, "\n");
    body.split("\n").forEach((line) => lines.push("        " + line));
    lines.push("    };");
    lines.push("");
});

lines.push("    __phase3Require('main.js');");
lines.push("})();");
lines.push("");

fs.writeFileSync(outFile, lines.join("\n"), "utf8");
console.log("Built " + outFile);
